TraditionalUserBundle:
    resource: "@TraditionalUserBundle/routing.yml"
    prefix: /traditional

#ModernUserBundle:
#    resource: "@ModernUserBundle/Resources/config/routing.yml"
#    prefix: /modern
